version: "3.9"

services:

  backend:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile_php
    container_name: offgroup_backend
    ports:
      - "8081:81"
    restart: unless-stopped
    volumes:
      - /var/www/html/offgroup/app:/app

  mysql:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile_mysql
    container_name: offgroup_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: offgroup
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
#    volumes:
#      - db-offgroup:/var/lib/mysql/

volumes:
  db-offgroup: