FROM alpine

RUN apk add  \
    php \
    php-fpm  \
    nginx  \
    php-pdo_mysql \
    php83-mysqlnd \
    php83-mysqli \
    composer \
    npm

#COPY /app /app
COPY ./.docker/nginx.conf /etc/nginx/nginx.conf
COPY ./.docker/php.ini /etc/php83/php.ini
COPY ./.docker/php-fpm.conf /etc/php83/php-fpm.conf

COPY ./.docker/entrypoint.sh entrypoint.sh
RUN chmod 777 entrypoint.sh

CMD ["./entrypoint.sh"]
EXPOSE 8081